/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.45
 * Generated at: 2019-09-10 02:53:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.ubi;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(9);
    _jspx_dependants.put("jar:file:/C:/Users/ems99/Desktop/team/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/UBIstudy/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/ubi/./../common/common.jsp", Long.valueOf(1567660071251L));
    _jspx_dependants.put("jar:file:/C:/Users/ems99/Desktop/team/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/UBIstudy/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/ubi/bottom.jsp", Long.valueOf(1567834518511L));
    _jspx_dependants.put("/WEB-INF/ubi/top.jsp", Long.valueOf(1567835093403L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1567659809589L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar", Long.valueOf(1567659784771L));
    _jspx_dependants.put("jar:file:/C:/Users/ems99/Desktop/team/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/UBIstudy/WEB-INF/lib/spring-webmvc-3.1.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1329370132000L));
    _jspx_dependants.put("jar:file:/C:/Users/ems99/Desktop/team/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/UBIstudy/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\r\n");
      out.write("\t#div1_1{\r\n");
      out.write("\t\tbackground-image: url(\"");
      out.print(request.getContextPath());
      out.write("/resources/images/project_img1.png\");\r\n");
      out.write("\t\tmin-width: 100%;\r\n");
      out.write("\t\theight: 500px;\r\n");
      out.write("\t\tz-index: 1;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t#divTop{\r\n");
      out.write("\t\tz-index: 2;\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#div2{\r\n");
      out.write("\t\tcolor: black;\r\n");
      out.write("\t}\r\n");
      out.write("\t#div1_obj1{\r\n");
      out.write("\t\tborder-bottom: 500px solid rgba(0,0,0,0.3);\r\n");
      out.write("\t\tborder-left: 50px solid transparent;\r\n");
      out.write("\t\theight: 0px;\r\n");
      out.write("\t\twidth: 400px;\r\n");
      out.write("\t\tfloat: right;\r\n");
      out.write("\t\tz-index: 1;\r\n");
      out.write("\t}\r\n");
      out.write("\t#div1_obj2{\r\n");
      out.write("\t\twidth: 700px;\r\n");
      out.write("\t\theight: 400px;\r\n");
      out.write("\t\tbackground-image: url(\"");
      out.print(request.getContextPath());
      out.write("/resources/images/project_img3.png\");\r\n");
      out.write("\t\tbackground-repeat:no-repeat;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tright: 120px;\r\n");
      out.write("\t\ttop: 70px;\r\n");
      out.write("\t\tz-index: 1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#div1_obj3{\r\n");
      out.write("\t\twidth: 200px;\r\n");
      out.write("\t\theight: 200px;\r\n");
      out.write("\t\tbackground-image: url(\"");
      out.print(request.getContextPath());
      out.write("/resources/images/project_img4.png\");\r\n");
      out.write("\t\tbackground-repeat:no-repeat;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 220px;\r\n");
      out.write("\t\ttop: 190px;\r\n");
      out.write("\t\topacity: 0.3;\r\n");
      out.write("\t}\r\n");
      out.write("\t.smallTitle1{\r\n");
      out.write("\t\tmargin-top:180px;\r\n");
      out.write("\t\tbackground-image: url(\"");
      out.print(request.getContextPath());
      out.write("/resources/images/project_img5.png\"); \r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t}\r\n");
      out.write("\t.smallTitle2{\r\n");
      out.write("\t\twidth: 70%;\r\n");
      out.write("\t\tborder-radius:10px 10px 10px 10px;\r\n");
      out.write("\t\tborder-right: 1px solid rgb(166,166,166);\r\n");
      out.write("\t\tborder-left: 1px solid rgb(166,166,166);\r\n");
      out.write("\t\tmargin: auto;\r\n");
      out.write("\t}\r\n");
      out.write("\t.smallTitle_title{color: rgb(166,166,166);font-size: 20px;}\r\n");
      out.write("\t.smallTitle_logo{color: rgb(217,217,217);}\r\n");
      out.write("\t.button2{\r\n");
      out.write("\t\tpadding: 15px;\r\n");
      out.write("\t\tborder: 1px solid #ccc;\r\n");
      out.write("\t\tbackground-color: white;\r\n");
      out.write("\t\tpadding-right:40px;\r\n");
      out.write("\t\tpadding-left:40px;\r\n");
      out.write("\t\tfont-size: 20px;\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.button2:hover{\r\n");
      out.write("\t\tborder: 1px solid #fa0;\r\n");
      out.write("\t\tcolor:#fa0;\r\n");
      out.write("\t}\r\n");
      out.write("\t#div3_img1{\r\n");
      out.write("\t\tbackground-image: url(\"");
      out.print(request.getContextPath());
      out.write("/resources/images/project_img2.png\");\r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t\theight: 588px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#div1_obj4{\r\n");
      out.write("\t\twidth: 0px;\r\n");
      out.write("\t\theight: 7px;\r\n");
      out.write("\t\tbackground-color:rgba(255,255,255,0.4);\r\n");
      out.write("\t\tbackground-repeat:no-repeat;\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 0px;\r\n");
      out.write("\t\ttop: 543px;\r\n");
      out.write("\t\topacity: 0.8;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar divNum=1;\r\n");
      out.write("\t\tvar div=\"#div1_\"+divNum;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.divContents').hide(0,function(){\r\n");
      out.write("\t\t\t$(div).show(\"fade\",800);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#div1_obj1').hide(0,function(){\r\n");
      out.write("\t\t\t$(this).show(\"drop\", {direction:\"right\"},1500);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('#div1_obj2').hide(0,function(){\r\n");
      out.write("\t\t\t$(this).show(\"drop\", {direction:\"up\"},1000);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#detail1').mouseover(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({color:'white'},300);\r\n");
      out.write("\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({color:'rgb(255,230,153)'},300);\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('#div1_obj3').mouseover(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({opacity:'1'},300);\r\n");
      out.write("\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({opacity:'0.3'},300);\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar i1=0;\r\n");
      out.write("\t\tvar i2=0;\r\n");
      out.write("\t\tvar i3=0;\r\n");
      out.write("\t\tvar today_user=672; \r\n");
      out.write("\t\tvar total_user=1568502;\r\n");
      out.write("\t\tvar some_number=689153;   \r\n");
      out.write("\t\tvar today_user_int = setInterval(function(){\r\n");
      out.write("\t\t\ti1+=Math.floor(today_user/500);\r\n");
      out.write("\t\t\t$('#today_user').html(i1+\"명\");\r\n");
      out.write("\t\t\tif(i1>=today_user){\r\n");
      out.write("\t\t\t\tclearTimeout(today_user_int);\r\n");
      out.write("\t\t\t\t$('#today_user').html(today_user+\"명\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},1);\r\n");
      out.write("\t\tvar total_user_int = setInterval(function(){\r\n");
      out.write("\t\t\ti2+=Math.floor(total_user/600);\r\n");
      out.write("\t\t\t$('#total_user').html(i2+\"명\");\r\n");
      out.write("\t\t\tif(i2>=total_user){\r\n");
      out.write("\t\t\t\tclearTimeout(total_user_int);\t\r\n");
      out.write("\t\t\t\t$('#total_user').html(total_user+\"명\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},1);\r\n");
      out.write("\t\tvar some_number_int = setInterval(function(){\r\n");
      out.write("\t\t\ti3+=Math.floor(some_number/700);\r\n");
      out.write("\t\t\t$('#some_number').html(i3);\r\n");
      out.write("\t\t\tif(i3>=some_number){\r\n");
      out.write("\t\t\t\tclearTimeout(some_number_int);\t\r\n");
      out.write("\t\t\t\t$('#some_number').html(some_number);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t},1);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar flag=true;\r\n");
      out.write("\t\tvar leng=1;\r\n");
      out.write("\t\tvar main = setInterval(function(){\r\n");
      out.write("\t\t\tif(flag==true){\r\n");
      out.write("\t\t\t\tleng+=1;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif((leng/2)>=100){\r\n");
      out.write("\t\t\t\tleng=0;\r\n");
      out.write("\t\t\t\t$(\"#div1_\"+divNum).hide(\"fade\",700,function(){\r\n");
      out.write("\t\t\t\t\tdivNum=divNum+1;\r\n");
      out.write("\t\t\t\t\tif(divNum>3){\r\n");
      out.write("\t\t\t\t\t\tdivNum=1;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#div1_\"+divNum).show(\"fade\",700);\t\t\t\t\t\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t$('.bar').animate({\r\n");
      out.write("\t\t\t\twidth:(leng/2)+\"%\"\r\n");
      out.write("\t\t\t},40);\r\n");
      out.write("\t\t},50);\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.divContents').mouseover(function(){\r\n");
      out.write("\t\t\tflag=false;\r\n");
      out.write("\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\tflag=true;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body style=\"overflow-x:hidden\">\r\n");
      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(" ");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t@font-face{\r\n");
      out.write("\t\tfont-family: 'NIXGONFONTS';\r\n");
      out.write("\t\tsrc: url(\"");
      out.print(request.getContextPath());
      out.write("/resources/font/NIXGONFONTS M 2.0.ttf\") format('truetype');\r\n");
      out.write("\t}\r\n");
      out.write("\tbody{\r\n");
      out.write("\t\tfont-family: NIXGONFONTS;\r\n");
      out.write("\t\t margin: 0;\r\n");
      out.write("    \tpadding: 0;\r\n");
      out.write("\t}\r\n");
      out.write("\tinput{\r\n");
      out.write("\t\tfont-family: NIXGONFONTS;\r\n");
      out.write("\t}\r\n");
      out.write("\t#divTop{\r\n");
      out.write("\t\tmin-width: 100%;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t\tbackground-color: rgba(0,0,0,1);\r\n");
      out.write("\t\t/* border-bottom: 1px solid rgba(133,119,105,1); */\r\n");
      out.write("\t\tbox-shadow: 0px 0px 5px 5px rgba(0,0,0,0.2);\r\n");
      out.write("\t}\r\n");
      out.write("\t#divTop_in{\r\n");
      out.write("\t\tmin-width: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t#top_mid span{\r\n");
      out.write("\t\tcolor: rgba(217,217,217,1);\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t#top_top{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tleft: 50px;\r\n");
      out.write("\t\ttop: 0px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#top_mid{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t\tpadding: 14px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#top_bot{\r\n");
      out.write("\t\tposition: absolute;\r\n");
      out.write("\t\tright:10px;\r\n");
      out.write("\t\ttop: 7px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.topBut1{\r\n");
      out.write("\t\tfont-size: 18px;\r\n");
      out.write("\t\tcursor:pointer;\t\t\r\n");
      out.write("\t}\r\n");
      out.write("\t.button1{\r\n");
      out.write("\t\tcursor:pointer;\t\t \r\n");
      out.write("\t\tborder-radius: 3px 3px 3px 3px;\r\n");
      out.write("\t\tborder: 1px solid rgb(150,150,150);\r\n");
      out.write("\t\tbackground-color: black;\r\n");
      out.write("\t\tfont-size:18px;\r\n");
      out.write("\t\tcolor: rgb(170,170,170);\r\n");
      out.write("\t\tpadding:6px;\r\n");
      out.write("\t\tpadding-left: 30px;\r\n");
      out.write("\t\tpadding-right: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t#gotoTop{\r\n");
      out.write("\t\tcursor: pointer;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\" src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(function(){\r\n");
      out.write("\t\tvar animationSpeed=300;\r\n");
      out.write("\t\t$('.topBut1').mouseover(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({\r\n");
      out.write("\t\t\t\tcolor:'rgb(255,217,102)'\r\n");
      out.write("\t\t\t},animationSpeed);\r\n");
      out.write("\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({\r\n");
      out.write("\t\t\t\tcolor:'rgb(217,217,217)'\r\n");
      out.write("\t\t\t},animationSpeed);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t$('.button1').mouseover(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({\r\n");
      out.write("\t\t\t\tbackgroundColor:'rgb(255,255,255)',\r\n");
      out.write("\t\t\t\tcolor:'black'\r\n");
      out.write("\t\t\t},animationSpeed);\r\n");
      out.write("\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({\r\n");
      out.write("\t\t\t\tbackgroundColor:'rgb(0,0,0)',\r\n");
      out.write("\t\t\t\tcolor:'rgb(170,170,170)'\r\n");
      out.write("\t\t\t},animationSpeed);\r\n");
      out.write("\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t$('#gotoTop').mouseover(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({\r\n");
      out.write("\t\t\t\tcolor:'rgba(255,192,0,1)'\r\n");
      out.write("\t\t\t},animationSpeed);\r\n");
      out.write("\t\t}).mouseout(function(){\r\n");
      out.write("\t\t\t$(this).stop().animate({\r\n");
      out.write("\t\t\t\tcolor:'rgba(0,0,0,0.2)'\r\n");
      out.write("\t\t\t},animationSpeed);\r\n");
      out.write("\t\t}).click(function(){\r\n");
      out.write("\t\t\t$('html, body').animate({\r\n");
      out.write("\t\t\t\t scrollTop : 0\r\n");
      out.write("\t\t\t}, 400);\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");

	String[] util={"스터디 그룹","동영상 강의","자유 게시판","공지"};

      out.write("\r\n");
      out.write("<div id=\"divTop\">\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"divTop_in\">\r\n");
      out.write("\t<div id=\"top_top\">\r\n");
      out.write("\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/logo1.png\" width=\"250px\" height=\"50px\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"top_mid\"><!--top메뉴의 중간 기능선택부분-->\r\n");
      out.write("\t\t<span class=\"topBut1\" id=\"");
      out.print(util[0]);
      out.write('"');
      out.write('>');
      out.print(util[0]);
      out.write("</span>\r\n");
      out.write("\t\t");
for(int i=1;i<util.length;i++){
      out.write("\t\r\n");
      out.write("\t\t<span>　│　</span>\r\n");
      out.write("\t\t<span class=\"topBut1\" id=\"");
      out.print(util[i]);
      out.write('"');
      out.write('>');
      out.print(util[i]);
      out.write("</span>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("\t</div>\t\r\n");
      out.write("\t<div id=\"top_bot\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"로그인\" id=\"login\" class=\"button1\">\r\n");
      out.write("\t\t<input type=\"button\" value=\"회원가입\" id=\"join\" class=\"button1\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"width: 100px;height: 130px; background-color: rgba(255,255,255,0.0);position: absolute; right: 50px; bottom: 0px; position: fixed;text-align: center;\">\r\n");
      out.write("\t<span id=\"gotoTop\" style=\"font-size: 40px;color: rgba(0,0,0,0.2);\">▲\r\n");
      out.write("\t<br>TOP\r\n");
      out.write("\t</span>\r\n");
      out.write("\t\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"div1_1\" class=\"divContents\">\r\n");
      out.write("\t<div id=\"div1_obj1\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"div1_obj2\" align=\"center\">\r\n");
      out.write("\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/logo1.png\" width=\"700px\" height=\"140px\">\r\n");
      out.write("\t\t<p style=\"color: rgb(255,242,204);font-size: 30px;\">유비쿼터스 뭔가 그런거 유비쿼터스</p>\r\n");
      out.write("\t\t<p style=\"text-align: left;margin-left: 107px;color: rgb(255,230,153);font-size: 20px;\">\r\n");
      out.write("\t\t대충 프로젝트의 설명같은 것. 긴 문장이어야 한다. 대충 그런<br> 내용들이다아아ㅏ아ㅏ아아아아아<br>\r\n");
      out.write("\t\t대충 강의에 대한 설명이나 사이트에<br>\r\n");
      out.write("\t\t대한 설명이나 그런거 \r\n");
      out.write("\t\t</p>\r\n");
      out.write("\t\t<p style=\"color: rgb(255,230,153);font-size: 30px;\" id=\"detail1\">▲<br>\r\n");
      out.write("\t\t자세히 보기 </p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"div1_obj3\">\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"div1_obj4\" class=\"bar\">\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div> \r\n");
      out.write("\r\n");
      out.write("<div id=\"div1_2\" class=\"divContents\" style=\"min-width: 100%;height: 500px;z-index: 1;cursor: pointer;\r\n");
      out.write("background-image: url('");
      out.print(request.getContextPath());
      out.write("/resources/images/project_img6.png');background-size: cover;\">\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t<div id=\"div1_obj4\" class=\"bar\">\r\n");
      out.write("\t</div>\t\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"div1_3\" class=\"divContents\" style=\"min-width: 100%;height: 500px;z-index: 1;cursor: pointer;\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"div1_obj4\" class=\"bar\">\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div style=\"background-color: black;height: 810px;box-shadow: 0px 0px 5px 5px rgba(0,0,0,0.2);padding-top: 200px;\">\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"color: white;text-align: center;font-size: 40px;\">\r\n");
      out.write("\t<span style=\"color: white;\">〔 대충 이 사이트를 이용하면 이득본다는 내용 〕</span>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<span style=\"color:rgba(207,175,100,1);\">\r\n");
      out.write("\t유비ㅎㅁㄷㄹㅇ리러훅ㄴㅇ날<br>;ㄴ이ㅗㅁㄹ너<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t：<br>\r\n");
      out.write("\t：<br>\r\n");
      out.write("\t：<br>\r\n");
      out.write("\t：<br>\r\n");
      out.write("\t</span>\t\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 오늘 개설된 스터디 그룹의 항목 -->\r\n");
      out.write("<div id=\"div2\" class=\"smallTitle1\" style=\"margin-top: 60px;\">\r\n");
      out.write("\t<div class=\"smallTitle2\">\r\n");
      out.write("\t\t<p class=\"smallTitle_title\">오늘 개설된 스터디 그룹</p>\r\n");
      out.write("\t\t<p class=\"smallTitle_logo\">UBI STUDY<br>\r\n");
      out.write("\t\t▼</p>\r\n");
      out.write("\t</div>\r\n");
for(int i=0;i<3;i++){ 
      out.write("\r\n");
      out.write("\t<div style=\"margin: auto;border-bottom:1px solid black;width: 1000px;height: 200px;margin-top: 50px;text-align: left;\">\r\n");
      out.write("\t\t<img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/default1.png\" style=\"float: left;margin-right: 20px;\" width=\"190px\" height=\"190px;\">\r\n");
      out.write("\t\t<span style=\"font-size:30px;\">title");
      out.print(i );
      out.write("</span>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<br>\r\n");
      out.write("\t\t<span style=\"font-size: 20px;\">contents/memo/");
      out.print(i );
      out.write("</span><br>\r\n");
      out.write("\t\t<p style=\"text-align: right;\"><input type=\"button\" value=\"참여\" class=\"button2\" id=\"");
      out.print(i);
      out.write("\"></p> \r\n");
      out.write("\t</div>\r\n");
}
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 조회수나 접속자 수를 나타내는 항목 -->\r\n");
      out.write("<div id=\"div3\" class=\"smallTitle1\">\r\n");
      out.write("\t<div class=\"smallTitle2\">\r\n");
      out.write("\t\t<p class=\"smallTitle_title\">UBI의 회원들</p>\r\n");
      out.write("\t\t<p class=\"smallTitle_logo\">UBI STUDY<br>\r\n");
      out.write("\t\t▼</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<br><br><br><br><br>\r\n");
      out.write("\t<div id=\"div3_img1\">\r\n");
      out.write("\t\t<div style=\"position: relative;top:233px;left: 210px;float: left;\">\r\n");
      out.write("\t\t\t<span style=\"color: rgb(197,90,17);font-size: 37px;border-bottom: 2px solid rgb(236,145,24);padding-bottom: 20px;\">\r\n");
      out.write("\t\t\t오늘 방문자 수\r\n");
      out.write("\t\t\t</span><br><br><br><br> \r\n");
      out.write("\t\t\t<span id=\"today_user\" style=\"color: rgb(132,60,12);font-size: 35px;\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"position: relative;top:233px;left: 430px;float: left;\">\r\n");
      out.write("\t\t\t<span style=\"color: rgb(236,137,28);font-size: 37px;border-bottom: 2px solid rgb(236,145,24);padding-bottom: 20px;\">\r\n");
      out.write("\t\t\t누적 방문자 수\r\n");
      out.write("\t\t\t</span><br><br><br><br> \r\n");
      out.write("\t\t\t<span id=\"total_user\" style=\"color: rgb(132,60,12);font-size: 35px;\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div style=\"position: relative;top:233px;left: 640px;float: left;\">\r\n");
      out.write("\t\t\t<span style=\"color: rgb(197,90,17);font-size: 37px;border-bottom: 2px solid rgb(236,145,24);padding-bottom: 20px;\">\r\n");
      out.write("\t\t\t그냥 뭔가 숫자\r\n");
      out.write("\t\t\t</span><br><br><br><br> \r\n");
      out.write("\t\t\t<span id=\"some_number\" style=\"color: rgb(132,60,12);font-size: 35px;\"></span>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- 대충 환영한다는 내용의 항목 -->\r\n");
      out.write("<div id=\"divLast\" class=\"smallTitle1\" style=\"height: 500px;\">\r\n");
      out.write("<br><br><br>\r\n");
      out.write("<br><br><br>\r\n");
      out.write("<br>\r\n");
      out.write("\t<div class=\"smallTitle2\" style=\"width: 500px;\">\r\n");
      out.write("\t\t<p class=\"smallTitle_title\" style=\"font-size: 30px;\">대충 환영한다는 내용</p>\r\n");
      out.write("\t\t<p class=\"smallTitle_logo\">UBI STUDY<br>\r\n");
      out.write("\t\t▼</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"bottom\" style=\"background-color: rgb(242,242,242);padding: 50px;border-top:2px solid rgb(166,166,166);color: rgb(150,150,150);\">\r\n");
      out.write("<p>\r\n");
      out.write("bottom.jsp<br>\r\n");
      out.write("가나다라마바사<br>\r\n");
      out.write("뭔가 작은 글씨들<br>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("(주)주주 / 공동대표 같은 건 없다/ 서울특별시 어딘가 / 사업자등록번호! / 통신판매업신고 제 2014-서울-03241호 / 직업정보제공사업<br>\r\n");
      out.write("신고번호 J1200020180027 / 유료직업소개사업 등록번호 (국내)제2019-3220237-14-5-00020호7<br>\r\n");
      out.write("▶ 강의 관련 문의 ─ 02.539.1????<br>\r\n");
      out.write("▶ 기업 서비스, 코딩 테스트 문의 ─ 02.539.????<br>\r\n");
      out.write("▶ 제휴 및 서비스 운영, 기타 문의 ─ 070.4107.????<br>\r\n");
      out.write("<br>\r\n");
      out.write("Abcdefghijklmnopqrstuvwxyz<br>\r\n");
      out.write("가나다<br>\r\n");
      out.write("라마바<br>\r\n");
      out.write("사아자ㅏㄴ마ㄴㅁ히ㅓㅇㄹ엉ㄹㄴㅇㄹㄴㄹㅇ\r\n");
      out.write("</p>\r\n");
      out.write("<p style=\"text-align: right;\"><img src=\"");
      out.print(request.getContextPath());
      out.write("/resources/images/logo3.png\" width=\"250px\" height=\"40px\"></p>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
